server:
  port: 8080

spring:
  datasource:
    #MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8
    username: root
    password: 134679
  mvc:
    # 配置静态资源路径
    static-path-pattern: /**
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB
mybatis:
  type-aliases-package: com.jph.myblog.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
shiro:
  loginUrl: /UserController/login
#    # 打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
## 打印sql
#logging:
#  level:
#    com.jph.myblog.mapper: trace
#pagehelper:
#  reasonable: true

